version: "3.8"

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    # Load environment variables from a .env file
    env_file:
      - .env
